### ISSUE TITLE
进入TG群的时候忘记点验证码，怎么重新进群

### ISSUE THREAD

**Issue by laolai** [SaltyLeo/i-book.in#2]
点进群之后，有事离开了，回来发现被永久BAN，怎么重新入群

**Comment by SaltyLeo** [comment]
可能是误删，请提供TG_username，我会将你从黑名单移除。

**Comment by laolai** [comment]
tyoopy

**Comment by laolai** [comment]
> 可能是误删，请提供TG_username，我会将你从黑名单移除。

tyoopy

**Comment by laolai** [comment]
> 可能是误删，请提供TG_username，我会将你从黑名单移除。

JuanAguacate
